### PR TITLE
Added startDate prop, replacing deprecated numDays

### PR DESCRIPTION
**Pull request by andreysaleba**

### CODE REVIEW

**Comment by okize** [comment]
@andreysaleba could you please resolve the merge conflict in `src/index.jsx`?

**Comment by andreysaleba** [comment]
@okize yeah, I'll do it tommorow

**Comment by andreysaleba** [comment]
@okize I've resolved the merge conflicts

**Comment by okize** [comment]
thanks @andreysaleba! published as v1.5.0

**Pull request merged**
